# Generated by Django 5.2.5 on 2025-09-09 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rbacaccesstoken",
            name="versions",
        ),
    ]
