CPU = 'CPU'
GPU = 'GPU'

MODEL_LOADING = 'LOADING'
MODEL_READY = 'READY'
MODEL_ERROR = 'ERROR'

SERVER_HEALTHY = 'HEALTHY'
SERVER_UNHEALTHY = 'UNHEALTHY'
SERVER_INIT = "INIT"

BEST_FIT = "BEST_FIT"
LEAST_LOADED = "LEAST_LOADED"
BIGGEST_FREE_MEMORY = "BIGGEST_FREE_MEMORY"

ROUND_ROBIN = "ROUND_ROBIN"
LEAST_SERVING = "LEAST_SERVING"
RANDOM = "RANDOM"
WEIGHTED_ROUND_ROBIN = "WEIGHTED_ROUND_ROBIN"

MODEL_DRAFT = "DRAFT"
MODEL_DEPLOYED = "DEPLOYED"
MODEL_ARCHIVED = "ARCHIVED"

INSTANCE_INIT = "INIT"