CPU = 'CPU'
GPU = 'GPU'

INSTANCE_LOADING = 'LOADING'
INSTANCE_READY = 'READY'
INSTANCE_ERROR = 'ERROR'
INSTANCE_INIT = "INIT"

SERVER_HEALTHY = 'HEALTHY'
SERVER_UNHEALTHY = 'UNHEALTHY'
SERVER_INIT = "INIT"

BEST_FIT = "BEST_FIT"
LEAST_LOADED = "LEAST_LOADED"
BIGGEST_FREE_MEMORY = "BIGGEST_FREE_MEMORY"

ROUND_ROBIN = "ROUND_ROBIN"
LEAST_SERVING = "LEAST_SERVING"
RANDOM = "RANDOM"
WEIGHTED_ROUND_ROBIN = "WEIGHTED_ROUND_ROBIN"

MODEL_DRAFT = "DRAFT"
MODEL_DEPLOYED = "DEPLOYED"
MODEL_ARCHIVED = "ARCHIVED"

VERSION_UNLOADED = "UNLOADED"
VERSION_DEPLOYED = "DEPLOYED"
VERSION_ARCHIVED = "ARCHIVED"
