CANT_DELETE_NON_ARCHIVED_MODEL = 'CANT_DELETE_NON_ARCHIVED_MODEL'
MODEL_ALREADY_DEPLOYED = 'MODEL_ALREADY_DEPLOYED'

TRITON_HTTP_URL_NOT_VALID = 'TRITON_HTTP_URL_NOT_VALID'
TRITON_GRPC_URL_NOT_VALID = 'TRITON_GRPC_URL_NOT_VALID'
TRITON_METRICS_URL_NOT_VALID = 'TRITON_METRICS_URL_NOT_VALID'
