# Generated by Django 5.2.5 on 2025-08-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
