# Generated by Django 5.2.5 on 2025-09-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_LOADED", "Not loaded"),
                    ("DEPLOYED", "Deployed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
