# Generated by Django 5.2.5 on 2025-09-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tritonserver",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
