# Generated by Django 5.2.5 on 2025-09-09 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0002_remove_rbacaccesstoken_versions"),
        ("orchestrator", "0002_modelversion_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelinstance",
            name="version",
        ),
        migrations.DeleteModel(
            name="ModelVersion",
        ),
    ]
