# Generated by Django 5.2.5 on 2025-08-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0002_model_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("DEPLOYING", "DEPLOYING"),
                    ("ARCHIVED", "ARCHIVED"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
