# Generated by Django 5.2.5 on 2025-08-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0003_model_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("DEPLOYED", "DEPLOYED"),
                    ("ARCHIVED", "ARCHIVED"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
