# Generated by Django 5.2.5 on 2025-08-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0004_alter_model_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tritonserver",
            name="address",
        ),
        migrations.AddField(
            model_name="tritonserver",
            name="grpc_url",
            field=models.CharField(default="http://localhost:8001", max_length=255),
        ),
        migrations.AddField(
            model_name="tritonserver",
            name="http_url",
            field=models.CharField(default="http://localhost:8000", max_length=255),
        ),
        migrations.AddField(
            model_name="tritonserver",
            name="metrics_url",
            field=models.CharField(default="http://localhost:8002", max_length=255),
        ),
    ]
