# Generated by Django 5.2.5 on 2025-08-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orchestrator",
            "0005_remove_tritonserver_address_tritonserver_grpc_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tritonserver",
            name="status",
            field=models.CharField(
                choices=[
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "Unhealthy"),
                    ("INIT", "Init"),
                ],
                default="INIT",
                max_length=16,
            ),
        ),
    ]
