# Generated by Django 5.2.5 on 2025-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0006_alter_tritonserver_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tritonserver",
            name="total_cpu_memory_mb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tritonserver",
            name="total_gpu_memory_mb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tritonserver",
            name="total_used_cpu_memory_mb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tritonserver",
            name="total_used_gpu_memory_mb",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
