# Generated by Django 5.2.5 on 2025-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0007_alter_tritonserver_total_cpu_memory_mb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tritonserver",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
