# Generated by Django 5.2.5 on 2025-08-29 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0008_alter_tritonserver_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tritonserver",
            name="grpc_url",
            field=models.TextField(
                default="http://localhost:8001",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="tritonserver",
            name="http_url",
            field=models.TextField(
                default="http://localhost:8000",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="tritonserver",
            name="metrics_url",
            field=models.TextField(
                default="http://localhost:8002",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
