# Generated by Django 5.2.5 on 2025-08-29 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0009_alter_tritonserver_grpc_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tritonserver",
            name="grpc_url",
            field=models.CharField(
                default="localhost:8001",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid host:port (e.g., 127.0.0.1:8001 or myhost:8001)",
                        regex="^[\\w\\.-]+:\\d+$",
                    )
                ],
            ),
        ),
    ]
