# Generated by Django 5.2.5 on 2025-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0010_alter_tritonserver_grpc_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="type",
            field=models.CharField(
                choices=[("cpu", "CPU"), ("gpu", "GPU")], default="gpu", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="tritonserver",
            name="type",
            field=models.CharField(
                choices=[("cpu", "CPU"), ("gpu", "GPU")], default="gpu", max_length=16
            ),
        ),
    ]
