# Generated by Django 5.2.5 on 2025-08-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0011_model_type_tritonserver_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("LOADING", "Loading"),
                    ("READY", "Ready"),
                    ("ERROR", "Error"),
                    ("INIT", "Init"),
                ],
                default="INIT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="name",
            field=models.IntegerField(default=1),
        ),
    ]
